branches:
  only:
    - /^webspoon-.*$/
language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install: true
script:
  - wget https://raw.githubusercontent.com/pentaho/maven-parent-poms/master/maven-support-files/settings.xml
  - mvn -s settings.xml clean source:jar package -pl legacy,kettle-plugins/common/ui
before_deploy:
  - git config --local user.name "Hiromu Hota"
  - git config --local user.email "hiromu.hota@hal.hitachi.com"
  - export TRAVIS_TAG=webspoon/nightly
  - git tag $TRAVIS_TAG --force
deploy:
  provider: releases
  api_key:
    secure: tdDghOPBsjSAyOJaAIw/q0y43iVihVuvyuO8lxib2iZPj2bcVWOdlIcB+qC6mX5B4kSQS9IC/W3B7klzkcdhL78CGLJii3F04EIzEt+1PNS+MOy5rlGX2fLF05vrcs4zMn1NlyhlDM1qDzQCIqTwGv5hHBYYQJDPgo5wiuA67umaVEYbLGIpey5TewLix62MaQu99WKgq43fETG8xkBx58Nt+MJ++0dNEwNRMvCnAuTKmi8kZOkZ+kxxg3DjNEbMzsu9Y1ybOTAnwndhlloMXkMdTN1ul6EM8UlnbhsMcNheHfb2zQoPDPad3K85WN5x/7BQs+aBfo9R/bdoI0KuUeNKblxLMdDDexAeebgaE73NiMFbYQbWwkZvPam5L01AjJPqPYMdmn7t747mJM1eTNVdEuDIFnGOGny/s+arUBql2/GkMDQFDE0Pxre3tfUgTDj4sMnW7arPSLZnwIe7H6Djj0yDOV/FIY6ZSMpQNLI/E3CtiLF2NJ/XIRe3zCTD2PGy9Y0LXaYrVWC+EJr9fVMxKXQWhrMOOWW3jFCPtENUWjWz1JxGBOwY/gnNPbs4vH0xnrPmCNvmU1RzhsK5M2CrgxUVHrX+FPMBO+TkFfBQ3uFtD7qBACuMiMF+K/1l1GBnWPtpAPBoEFzbMoVYN9Y1dGmHyw+lPRXT2HfXEzI=
  file_glob: true
  file:
    - legacy/target/pentaho-big-data-legacy-*.jar
    - kettle-plugins/common/ui/target/pentaho-big-data-kettle-plugins-common-ui-*.jar
  skip_cleanup: true
  on:
    branch: webspoon-8.2
  name: webSpoon/nightly
  prerelease: true
  overwrite: true
